version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./zinlink_front/project:/app/zinlink_front/project
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./zinlink_project/admin_zinlink:/var/www/zinlink/project/admin_zinlink
    command: php artisan serve --host=0.0.0.0 --port=8000
