<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Gaming Laptops
            [
                'name' => 'ROG Strix G15',
                'description' => 'High-performance gaming laptop with RTX 4060 graphics, perfect for gaming and content creation.',
                'price' => 185000,
                'brand' => 'ASUS',
                'model' => 'G15-2024',
                'processor' => 'Intel Core i7-13700H',
                'ram' => '16GB DDR5',
                'storage' => '512GB NVMe SSD',
                'display' => '15.6" FHD 144Hz',
                'graphics' => 'NVIDIA RTX 4060 8GB',
                'operating_system' => 'Windows 11 Home',
                'stock_quantity' => 8,
                'category' => 'gaming-laptop',
                'condition' => 'new',
                'warranty' => '2 Years',
                'is_active' => true,
            ],
            [
                'name' => 'Legion Pro 7',
                'description' => 'Premium gaming laptop with RTX 4080 graphics, designed for serious gamers and professionals.',
                'price' => 320000,
                'brand' => 'Lenovo',
                'model' => 'Pro 7-16IRX8',
                'processor' => 'Intel Core i9-13900HX',
                'ram' => '32GB DDR5',
                'storage' => '1TB NVMe SSD',
                'display' => '16" QHD 240Hz',
                'graphics' => 'NVIDIA RTX 4080 12GB',
                'operating_system' => 'Windows 11 Pro',
                'stock_quantity' => 5,
                'category' => 'gaming-laptop',
                'condition' => 'new',
                'warranty' => '3 Years',
                'is_active' => true,
            ],
            [
                'name' => 'Alienware x16',
                'description' => 'Ultra-premium gaming laptop with RTX 4090 graphics, the ultimate gaming experience.',
                'price' => 450000,
                'brand' => 'Dell',
                'model' => 'x16-R1',
                'processor' => 'Intel Core i9-13900HK',
                'ram' => '64GB DDR5',
                'storage' => '2TB NVMe SSD',
                'display' => '16" QHD+ 240Hz',
                'graphics' => 'NVIDIA RTX 4090 16GB',
                'operating_system' => 'Windows 11 Pro',
                'stock_quantity' => 3,
                'category' => 'gaming-laptop',
                'condition' => 'new',
                'warranty' => '3 Years',
                'is_active' => true,
            ],

            // Regular Laptops
            [
                'name' => 'MacBook Air M2',
                'description' => 'Ultra-thin and light laptop with Apple M2 chip, perfect for productivity and creativity.',
                'price' => 180000,
                'brand' => 'Apple',
                'model' => 'MacBook Air M2',
                'processor' => 'Apple M2',
                'ram' => '8GB Unified Memory',
                'storage' => '256GB SSD',
                'display' => '13.6" Liquid Retina',
                'graphics' => 'Integrated 10-core GPU',
                'operating_system' => 'macOS Ventura',
                'stock_quantity' => 12,
                'category' => 'laptop',
                'condition' => 'new',
                'warranty' => '1 Year',
                'is_active' => true,
            ],
            [
                'name' => 'ThinkPad X1 Carbon',
                'description' => 'Premium business laptop with exceptional build quality and security features.',
                'price' => 220000,
                'brand' => 'Lenovo',
                'model' => 'X1 Carbon Gen 11',
                'processor' => 'Intel Core i7-1355U',
                'ram' => '16GB LPDDR5',
                'storage' => '512GB NVMe SSD',
                'display' => '14" 2.8K OLED',
                'graphics' => 'Intel Iris Xe',
                'operating_system' => 'Windows 11 Pro',
                'stock_quantity' => 10,
                'category' => 'laptop',
                'condition' => 'new',
                'warranty' => '3 Years',
                'is_active' => true,
            ],
            [
                'name' => 'Dell XPS 13 Plus',
                'description' => 'Ultra-modern laptop with edge-to-edge display and premium design.',
                'price' => 195000,
                'brand' => 'Dell',
                'model' => 'XPS 13 Plus 9320',
                'processor' => 'Intel Core i7-1360P',
                'ram' => '16GB LPDDR5',
                'storage' => '512GB NVMe SSD',
                'display' => '13.4" 4K OLED',
                'graphics' => 'Intel Iris Xe',
                'operating_system' => 'Windows 11 Home',
                'stock_quantity' => 7,
                'category' => 'laptop',
                'condition' => 'new',
                'warranty' => '2 Years',
                'is_active' => true,
            ],

            // Desktop Computers
            [
                'name' => 'iMac 24" M3',
                'description' => 'All-in-one desktop with Apple M3 chip, perfect for home and office use.',
                'price' => 250000,
                'brand' => 'Apple',
                'model' => 'iMac M3',
                'processor' => 'Apple M3',
                'ram' => '8GB Unified Memory',
                'storage' => '256GB SSD',
                'display' => '24" 4.5K Retina',
                'graphics' => 'Integrated 10-core GPU',
                'operating_system' => 'macOS Sonoma',
                'stock_quantity' => 6,
                'category' => 'desktop',
                'condition' => 'new',
                'warranty' => '1 Year',
                'is_active' => true,
            ],
            [
                'name' => 'HP Pavilion Desktop',
                'description' => 'Powerful desktop computer for home and office productivity.',
                'price' => 85000,
                'brand' => 'HP',
                'model' => 'Pavilion TP01',
                'processor' => 'AMD Ryzen 5 5600G',
                'ram' => '16GB DDR4',
                'storage' => '512GB SSD',
                'display' => '21.5" FHD',
                'graphics' => 'AMD Radeon Graphics',
                'operating_system' => 'Windows 11 Home',
                'stock_quantity' => 15,
                'category' => 'desktop',
                'condition' => 'new',
                'warranty' => '2 Years',
                'is_active' => true,
            ],

            // CCTV Systems
            [
                'name' => 'Hikvision 4K DVR Kit',
                'description' => 'Complete 4K surveillance system with 8 cameras and 2TB storage.',
                'price' => 45000,
                'brand' => 'Hikvision',
                'model' => 'DS-7308HQHI-K1',
                'processor' => 'H.264/H.265',
                'ram' => '4GB DDR3',
                'storage' => '2TB HDD',
                'display' => '8 Channel DVR',
                'graphics' => 'Integrated',
                'operating_system' => 'Embedded Linux',
                'stock_quantity' => 20,
                'category' => 'cctv',
                'condition' => 'new',
                'warranty' => '2 Years',
                'is_active' => true,
            ],

            // Laptop Chargers
            [
                'name' => 'Universal Laptop Charger',
                'description' => 'Universal 90W laptop charger compatible with most brands.',
                'price' => 3500,
                'brand' => 'Generic',
                'model' => 'UC-90W',
                'processor' => 'N/A',
                'ram' => 'N/A',
                'storage' => 'N/A',
                'display' => 'N/A',
                'graphics' => 'N/A',
                'operating_system' => 'N/A',
                'stock_quantity' => 50,
                'category' => 'laptop chargers',
                'condition' => 'new',
                'warranty' => '1 Year',
                'is_active' => true,
            ],

            // Hard Disk/SSD
            [
                'name' => 'Samsung 970 EVO Plus 1TB',
                'description' => 'High-performance NVMe SSD with read speeds up to 3,500MB/s.',
                'price' => 12000,
                'brand' => 'Samsung',
                'model' => 'MZ-V7S1T0BW',
                'processor' => 'N/A',
                'ram' => 'N/A',
                'storage' => '1TB NVMe SSD',
                'display' => 'N/A',
                'graphics' => 'N/A',
                'operating_system' => 'N/A',
                'stock_quantity' => 25,
                'category' => 'harddisk/ssd',
                'condition' => 'new',
                'warranty' => '5 Years',
                'is_active' => true,
            ],

            // WiFi Equipment
            [
                'name' => 'TP-Link Archer C6',
                'description' => 'Dual-band WiFi 5 router with Gigabit ports and MU-MIMO technology.',
                'price' => 8500,
                'brand' => 'TP-Link',
                'model' => 'Archer C6',
                'processor' => 'N/A',
                'ram' => 'N/A',
                'storage' => 'N/A',
                'display' => 'N/A',
                'graphics' => 'N/A',
                'operating_system' => 'Embedded',
                'stock_quantity' => 30,
                'category' => 'wifi',
                'condition' => 'new',
                'warranty' => '2 Years',
                'is_active' => true,
            ],

            // Other Accessories
            [
                'name' => 'Logitech MX Master 3',
                'description' => 'Premium wireless mouse with precision scrolling and customizable buttons.',
                'price' => 8500,
                'brand' => 'Logitech',
                'model' => 'MX Master 3',
                'processor' => 'N/A',
                'ram' => 'N/A',
                'storage' => 'N/A',
                'display' => 'N/A',
                'graphics' => 'N/A',
                'operating_system' => 'Cross-platform',
                'stock_quantity' => 40,
                'category' => 'other accessories',
                'condition' => 'new',
                'warranty' => '2 Years',
                'is_active' => true,
            ],

            // ZINBook Series
            [
                'name' => 'ZINBook Pro X1',
                'description' => 'The ZINBook Pro X1 combines exceptional performance with ultra-portability. Its stunning OLED display delivers vibrant colors and deep blacks, while the powerful Intel processor handles demanding tasks with ease. Perfect for professionals, creators, and anyone who values premium design and performance.',
                'price' => 130000,
                'brand' => 'ZINLink',
                'model' => 'Pro X1',
                'processor' => 'Intel Core i7-12700H',
                'ram' => '16GB DDR5',
                'storage' => '512GB NVMe SSD',
                'display' => '14-inch 2.8K (2880 x 1800) OLED, 90Hz',
                'graphics' => 'Intel Iris Xe Graphics',
                'operating_system' => 'Windows 11 Home',
                'stock_quantity' => 10,
                'image_url' => 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                'category' => 'ultrabook',
                'condition' => 'new',
                'warranty' => '1 Year',
                'is_active' => true,
            ],
            [
                'name' => 'ZINBook Gaming Ultra',
                'description' => 'Dominate your games with the ZINBook Gaming Ultra. Featuring a powerful AMD Ryzen processor and NVIDIA RTX graphics, this laptop delivers exceptional frame rates even in the most demanding titles. The high-refresh-rate display ensures smooth gameplay, while advanced cooling keeps performance consistent during extended gaming sessions.',
                'price' => 180000,
                'brand' => 'ZINLink',
                'model' => 'Gaming Ultra',
                'processor' => 'AMD Ryzen 9 7900X',
                'ram' => '32GB DDR5',
                'storage' => '1TB NVMe SSD',
                'display' => '15.6-inch QHD (2560 x 1440) IPS, 165Hz',
                'graphics' => 'NVIDIA GeForce RTX 4070, 8GB GDDR6',
                'operating_system' => 'Windows 11 Home',
                'stock_quantity' => 7,
                'image_url' => 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                'category' => 'gaming',
                'condition' => 'new',
                'warranty' => '2 Years',
                'is_active' => true,
            ],
            [
                'name' => 'ZINBook Pro Workstation',
                'description' => 'Engineered for professional content creators and developers, the ZINBook Pro Workstation delivers desktop-class performance in a mobile form factor. The stunning 4K Mini-LED display offers exceptional color accuracy and brightness, while the powerful components handle resource-intensive applications with ease. ISV certified for professional software.',
                'price' => 250000,
                'brand' => 'ZINLink',
                'model' => 'Pro Workstation',
                'processor' => 'Intel Core i9-13900K',
                'ram' => '64GB DDR5',
                'storage' => '2TB NVMe SSD',
                'display' => '16-inch 4K (3840 x 2400) Mini-LED',
                'graphics' => 'NVIDIA RTX A5000, 16GB GDDR6',
                'operating_system' => 'Windows 11 Pro',
                'stock_quantity' => 5,
                'image_url' => 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                'category' => 'workstation',
                'condition' => 'new',
                'warranty' => '3 Years',
                'is_active' => true,
            ],
            [
                'name' => 'ZINBook Creator Pro',
                'description' => 'Designed for content creators, the ZINBook Creator Pro features a stunning OLED display with exceptional color accuracy (100% DCI-P3, Pantone Validated). The powerful processor and graphics card handle video editing, 3D rendering, and other creative tasks with ease, while the comprehensive connectivity options accommodate all your peripherals.',
                'price' => 190000,
                'brand' => 'ZINLink',
                'model' => 'Creator Pro',
                'processor' => 'AMD Ryzen 9 7940HS',
                'ram' => '32GB DDR5',
                'storage' => '1TB NVMe SSD',
                'display' => '16-inch 3K (3072 x 1920) OLED, 120Hz',
                'graphics' => 'NVIDIA GeForce RTX 4060, 8GB GDDR6',
                'operating_system' => 'Windows 11 Home',
                'stock_quantity' => 6,
                'image_url' => 'https://images.pexels.com/photos/40185/mac-freelancer-macintosh-macbook-40185.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
                'category' => 'creator',
                'condition' => 'new',
                'warranty' => '2 Years',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
